@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0\.."

REM ============================================================
REM  CCA v6.2 - autonomous launcher TEMPLATE
REM ============================================================
REM  Drives the full pipeline on one host for a contiguous range
REM  of chapters of ONE subject. Designed to be invoked by a
REM  scheduled task on hosts where the user (e.g. host-1) is
REM  logged on to the console.
REM
REM  REQUIRED ENV VARS (set before invoking, e.g. in a wrapper):
REM    CCA_GRADE          e.g. 10
REM    CCA_LANG           e.g. uz
REM    CCA_SUBJECT        e.g. "jahon tarixi"
REM    CCA_CHAPTERS       comma-separated, e.g. 1,2,3
REM    NOTION_API_KEY     ntn_...
REM    CHATGPT_EMAIL      account email
REM    CHATGPT_PASSWORD   account password
REM    GEMINI_EMAIL       primary account email
REM    GEMINI_PASSWORD    primary account password
REM
REM  OPTIONAL:
REM    CCA_ZIP_PREFIX     default: ""
REM    CDP_PORT           default: 9222
REM    GEMINI_CDP_PORT    default: 9223
REM    ACCOUNTS_JSON      raw JSON for accounts.json (with multiple gemini accounts)
REM
REM  Outputs:
REM    .env, accounts.json, lessons.txt (auto-generated in repo root)
REM    Per-chapter fetch/refine/prompts/images via scripts\run_pipeline.cjs
REM    Background dashboard at http://<host-ip>:7777 (binds 0.0.0.0)
REM ============================================================

REM --- Auto-discover per-user Python (when launcher runs under SYSTEM context) ---
if not defined PYTHON_HOME (
  for /d %%U in (C:\Users\*) do (
    if exist "%%U\AppData\Local\Programs\Python\Python312\python.exe" (
      set "PYTHON_HOME=%%U\AppData\Local\Programs\Python\Python312"
      set "PYTHON_LAUNCHER=%%U\AppData\Local\Programs\Python\Launcher"
    )
  )
)
if defined PYTHON_HOME (
  set "PATH=!PYTHON_HOME!;!PYTHON_HOME!\Scripts;!PYTHON_LAUNCHER!;%PATH%"
  echo Python found: !PYTHON_HOME!
) else (
  echo WARN: Python312 not found under any C:\Users\*\AppData\Local\Programs\Python\
)

REM --- Validate required env vars ---
if not defined CCA_GRADE        (echo ERROR: CCA_GRADE not set & exit /b 2)
if not defined CCA_LANG         (echo ERROR: CCA_LANG not set & exit /b 2)
if not defined CCA_SUBJECT      (echo ERROR: CCA_SUBJECT not set & exit /b 2)
if not defined CCA_CHAPTERS     (echo ERROR: CCA_CHAPTERS not set & exit /b 2)
if not defined NOTION_API_KEY   (echo ERROR: NOTION_API_KEY not set & exit /b 2)
if not defined CHATGPT_EMAIL    (echo ERROR: CHATGPT_EMAIL not set & exit /b 2)
if not defined CHATGPT_PASSWORD (echo ERROR: CHATGPT_PASSWORD not set & exit /b 2)
if not defined GEMINI_EMAIL     (echo ERROR: GEMINI_EMAIL not set & exit /b 2)
if not defined GEMINI_PASSWORD  (echo ERROR: GEMINI_PASSWORD not set & exit /b 2)

if not exist "src\node\orchestrators\run_pipeline.cjs" (echo ERROR: src\node\orchestrators\run_pipeline.cjs not found. & exit /b 1)

REM --- Pull latest (non-fatal) ---
where git >nul 2>nul
if not errorlevel 1 git pull --ff-only origin main 2>nul
git log --oneline -1 2>nul

REM --- Write .env ---
echo Writing .env...
(
  echo # Auto-generated by launch_template.bat - do not commit
  echo NOTION_API_KEY=%NOTION_API_KEY%
  echo CHATGPT_EMAIL=%CHATGPT_EMAIL%
  echo CHATGPT_PASSWORD=%CHATGPT_PASSWORD%
  echo GEMINI_EMAIL=%GEMINI_EMAIL%
  echo GEMINI_PASSWORD=%GEMINI_PASSWORD%
  echo CDP_PORT=%CDP_PORT%
  echo GEMINI_CDP_PORT=%GEMINI_CDP_PORT%
) > .env
if not defined CDP_PORT        echo CDP_PORT=9222 >> .env
if not defined GEMINI_CDP_PORT echo GEMINI_CDP_PORT=9223 >> .env

REM --- Write accounts.json ---
if defined ACCOUNTS_JSON (
  echo Writing accounts.json from $ACCOUNTS_JSON env var...
  echo %ACCOUNTS_JSON% > accounts.json
) else (
  echo Writing minimal accounts.json (primary creds only)...
  (
    echo {
    echo   "chatgpt": [
    echo     { "label": "primary", "email": "%CHATGPT_EMAIL%", "password": "%CHATGPT_PASSWORD%" }
    echo   ],
    echo   "gemini": [
    echo     { "label": "primary", "email": "%GEMINI_EMAIL%", "password": "%GEMINI_PASSWORD%" }
    echo   ]
    echo }
  ) > accounts.json
)

REM --- Write lessons.txt (one line per chapter, first line includes grade/lang/subject) ---
echo Writing lessons.txt...
set _FIRST=1
( for %%C in (%CCA_CHAPTERS%) do (
    if "!_FIRST!"=="1" (
      echo %CCA_GRADE%,%CCA_LANG%,%CCA_SUBJECT%,%%C
      set _FIRST=0
    ) else (
      echo %%C
    )
  )
) > lessons.txt

REM --- Prereqs ---
where node >nul 2>nul   || (echo ERROR Node missing.   & exit /b 1)
where python >nul 2>nul || (echo ERROR Python missing. & exit /b 1)

REM --- Reset rotators ---
python -m src.python.auth.accounts reset chatgpt 2>nul
python -m src.python.auth.accounts reset gemini 2>nul
python -m src.python.auth.accounts status

REM --- Install deps ---
set PUPPETEER_SKIP_DOWNLOAD=true
set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
where npm >nul 2>nul
if errorlevel 1 (
  if exist "%PROGRAMFILES%\nodejs\npm.cmd" call "%PROGRAMFILES%\nodejs\npm.cmd" install --silent
) else (
  call npm install --silent
)
python -m pip install -q -r requirements.txt

REM --- Chrome ---
node src\node\setup\setup_chrome.cjs || (echo ERROR setup_chrome failed. & exit /b 1)

REM --- Dashboard (background) ---
for /f "tokens=2 delims=:" %%i in ('ipconfig ^| findstr /R /C:"IPv4.*192\.168\."') do set "MY_IP=%%i"
set "MY_IP=%MY_IP: =%"
start "CCA Dashboard" cmd /k "node src\node\dashboard\dashboard.cjs"
timeout /t 3 /nobreak >nul
echo Dashboard URL: http://%MY_IP%:7777   (or http://localhost:7777 from this host)
start "" "http://localhost:7777"

REM --- Auto-login (60s grace if it fails) ---
python src\python\auth\auto_login.py
set AL_RC=%errorlevel%
if not "%AL_RC%"=="0" (
  echo Auto-login rc=%AL_RC% - waiting 60s for manual sign-in
  timeout /t 60 /nobreak >nul
)

REM --- ChatGPT account spinner (background, opt-in via CCA_ENABLE_CHATGPT_SPINNER=1) ---
REM Mirrors the Gemini autonomous rotation pattern: a long-running watcher polls
REM the ChatGPT chrome (:9222) for account-level blockers (quota / rate-limit /
REM session-expired) and writes alerts to .cca/chatgpt_alerts.json. The
REM orchestrator (run_pipeline.cjs) rotates pre-emptively before the next
REM REFINE/PROMPTS stage when alerts warrant it.
if /I "%CCA_ENABLE_CHATGPT_SPINNER%"=="1" (
  start "CCA ChatGPT Spinner" cmd /k "node src\node\workers\chatgpt_monitor.cjs --watch"
  echo ChatGPT spinner started in background.
)

REM --- Pipeline loop ---
set CCA_GRADE=%CCA_GRADE%
set CCA_LANG=%CCA_LANG%
set CCA_SUBJECT=%CCA_SUBJECT%

echo.
echo ============================================================
echo   STARTING PIPELINE - chapters: %CCA_CHAPTERS%
echo   Dashboard: http://%MY_IP%:7777
echo ============================================================

set LAST_RC=0
for %%C in (%CCA_CHAPTERS%) do (
  echo.
  echo ###############################################################
  echo #  CHAPTER %%C  : G%CCA_GRADE% / %CCA_SUBJECT% / ch %%C
  echo ###############################################################
  set CCA_CHAPTER=%%C
  node src\node\orchestrators\run_pipeline.cjs <nul
  set LAST_RC=!errorlevel!
  echo Chapter %%C finished. Exit code: !LAST_RC!
)

echo.
echo ============================================================
echo   BATCH SUMMARY  (chapters: %CCA_CHAPTERS%)
echo ============================================================
python -m src.python.auth.accounts status
echo   Dashboard: http://%MY_IP%:7777
echo   Last chapter exit code: %LAST_RC%
echo ============================================================

REM Exit cleanly (do NOT `cmd /k` — that hangs schtasks tasks).
exit /b %LAST_RC%
